---
# This is a simple playbook with two plays

- name: First play
  hosts: vms
  tasks:
    - name: First task
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Second task
      ansible.builtin.service:
        name: httpd
        enabled: true

- name: Second play
  hosts: vms
  tasks:
    - name: First task
      ansible.builtin.service:
        name: mariadb
        enabled: true
