- name: playbook
  hosts: vms
  user: lamarach
  become: true
  tasks:
    - name: Print all facts
      ansible.builtin.debug:
       var: ansible_facts
    - name: Install git on the vm
      dnf:
       name: 
        - git
        - podman
